#!/bin/bash

# Description:
# This script will detect the system's OS, then apply the dotfile configs for that system type.

# Grabbing the OS type from the /etc/os-release file, scoping the shellcheck directive to only this function
getOsType() {
  # shellcheck disable=SC1091
  source /etc/os-release

  echo "${ID_LIKE}"
}
OS_TYPE=$(getOsType)

# Grabbing the script's directory
SCRIPT_PATH="$(realpath "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "${SCRIPT_PATH}")"

symLink() {
  local originPath="$1"
  local targetPath="$2"

  [[ ! -f "${originPath}" ]] && echo "symLink: Invalid origin path." && exit 1

  ln -sf "${originPath}" "${targetPath}"
}

# Starship Configs
symLink "${SCRIPT_DIR}/starship/starship.toml" ~/.config/starship.toml
echo "NOTE: Starship requires adding \`eval \"\$(starship init bash)\"\` to your \$HOME/.bashrc file"

# Tmux configs
symLink "${SCRIPT_DIR}/tmux/tmux.conf" ~/.tmux.conf

# EDITOR to vim
if [[ "${EDITOR}" != "vim" ]]; then
  echo "NOTE: Your current EDITOR is not set to vim."
  echo "Consider running \`echo \"export EDITOR=vim\" >> \${HOME}/.bashrc ; source \${HOME}/.bashrc\`"
fi

# Vimrc configs
if [[ "${#OS_TYPE}" -gt 0 ]]; then
  symLink "${SCRIPT_DIR}/vimrc/${OS_TYPE}-vimrc" ~/.vimrc
fi

# LazyVim Configs
if [[ -d "${HOME}/.config/nvim" ]]; then
  HOME_NVIM="${HOME}/.config/nvim"
  HOME_PLUGINS="${HOME_NVIM}/lua/plugins"

  LUA_DIR="${SCRIPT_DIR}/nvim/lua"
  PLUGINS_DIR="${LUA_DIR}/plugins"

  # Setting the configs
  symLink "${LUA_DIR}/config/0_config.lua" "${HOME_NVIM}/lua/config/0_config.lua"

  # Setting the plugins
  symLink "${PLUGINS_DIR}/claude.lua" "${HOME_PLUGINS}/claude.lua"
  symLink "${PLUGINS_DIR}/codecompanion.lua" "${HOME_PLUGINS}/codecompanion.lua"
  symLink "${PLUGINS_DIR}/noice.lua" "${HOME_PLUGINS}/noice.lua"
  symLink "${PLUGINS_DIR}/pandoc.lua" "${HOME_PLUGINS}/pandoc.lua"
  symLink "${PLUGINS_DIR}/snacks.lua" "${HOME_PLUGINS}/snacks.lua"
fi

# Claude-Code configs
[[ -d "${HOME}/.claude" ]] && symLink "${SCRIPT_DIR}/claude/CLAUDE.md" ~/.claude/CLAUDE.md

# TODO: Add other dotfile configs as needed
