#!/bin/bash

# Description:
# This script will detect the system's OS, then apply the dotfile configs for that system type.

# Grabbing the OS type from the /etc/os-release file, scoping the shellcheck directive to only this function
getOsType() {
  # shellcheck disable=SC1091
  source /etc/os-release

  echo "${ID_LIKE}"
}
OS_TYPE=$(getOsType)

# Grabbing the script's directory
SCRIPT_PATH="$(realpath "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "${SCRIPT_PATH}")"

symLink() {
  local originPath="$1"
  local targetPath="$2"

  [[ ! -f "${originPath}" ]] && echo "symLink: Invalid origin path: ${originPath}" && exit 1

  echo "Creating symlink for ${originPath}"
  ln -sf "${originPath}" "${targetPath}"
}

# Takes in an origin directory, a target directory, and a string for plugin names.
# Usage: symLinkNvimPlugins ~/scripts/dotfiles/nvim/lua/plugins ~/.config/nvim/lua/plugins "claude colorscheme noice"
symLinkNvimConfigs() {
  local scriptDir="$1"
  local targetDir="$2"
  local -a plugins

  # Reading third argument as array
  IFS=' ' read -ra plugins <<<"$3"

  # Create the sym links for all plugins
  for plugin in "${plugins[@]}"; do
    symLink "${scriptDir}/${plugin}.lua" "${targetDir}/${plugin}.lua"
  done
}

# Starship Configs
symLink "${SCRIPT_DIR}/starship/starship.toml" ~/.config/starship.toml
echo "NOTE: Starship requires adding \`eval \"\$(starship init bash)\"\` to your \$HOME/.bashrc file"

# Tmux configs
symLink "${SCRIPT_DIR}/tmux/tmux.conf" ~/.tmux.conf

# EDITOR to vim
if [[ "${EDITOR}" != "vim" ]]; then
  echo "NOTE: Your current EDITOR is not set to vim."
  echo "Consider running \`echo \"export EDITOR=vim\" >> \${HOME}/.bashrc ; source \${HOME}/.bashrc\`"
fi

# Vimrc configs
if [[ "${#OS_TYPE}" -gt 0 ]]; then
  symLink "${SCRIPT_DIR}/vimrc/${OS_TYPE}-vimrc" ~/.vimrc
fi

# LazyVim Configs
if [[ -d "${HOME}/.config/nvim" ]]; then
  HOME_NVIM="${HOME}/.config/nvim"
  HOME_PLUGINS="${HOME_NVIM}/lua/plugins"

  SCRIPT_LUA="${SCRIPT_DIR}/nvim/lua"
  SCRIPT_PLUGINS="${SCRIPT_LUA}/plugins"

  # Adding the readme file
  symLink "${SCRIPT_DIR}/nvim/README.md" ~/.config/nvim/README.md

  # Adding the init file
  symLink "${SCRIPT_DIR}/nvim/init.lua" ~/.config/nvim/init.lua

  # Setting the configs
  NVIM_CONFIGS="0_config lsp"
  symLinkNvimConfigs "${SCRIPT_LUA}/config" ~/.config/nvim/lua/config "${NVIM_CONFIGS}"

  # Setting the plugins
  NVIM_PLUGINS="buffertabs claude codecompanion colorscheme conform fzf lazygit pandoc snacks treesitter whichkey"
  symLinkNvimConfigs "${SCRIPT_PLUGINS}" "${HOME_PLUGINS}" "${NVIM_PLUGINS}"
fi

# Claude-Code configs
[[ -d "${HOME}/.claude" ]] && symLink "${SCRIPT_DIR}/claude/CLAUDE.md" ~/.claude/CLAUDE.md

# TODO: Add other dotfile configs as needed
