#!/bin/bash

flatpak install \
  com.github.tchx84.Flatseal \
  md.obsidian.Obsidian \
  com.brave.Browser \
  com.discordapp.Discord \
  org.telegram.desktop \
  com.spotify.Client \
  com.valvesoftware.Steam \
  io.github.limo_app.limo \
  net.davidotek.pupgui2 \
  org.dupot.easyflatpak \
  org.videolan.VLC
