#!/bin/bash

# Converts text to a URL slug (e.g., "Some sort of text!" -> some-sort-of-text)
read -r line
line="${line,,}"
line="${line//[^a-z0-9]/-}"
line="${line//+(-)/-}" # remove repeating '-' characters
line="${line#-}"       # leading -
line="${line%-}"       # remove trailing -
echo "${line}"
